package trace2syz

type pair struct {
	A string
	B string
}

var (
	unsupported = map[string]bool{
		"brk":                    true,
		"":                       true,
		"execve":                 true, // unsupported
		"access":                 true, // unsupported
		"gettimeofday":           true, // unsupported
		"kill":                   true, // unsupported
		"arch_prctl":             true,
		"getcwd":                 true, // unsupported
		"setdomainname":          true, // unsupported
		"reboot":                 true, // unsupported
		"getppid":                true, // unsupported
		"umask":                  true, // unsupported
		"adjtimex":               true, // unsupported
		"nanosleep":              true,
		"wait4":                  true,
		"wait":                   true,
		"futex":                  true,
		"rt_sigprocmask":         true,
		"rt_sigaction":           true,
		"rt_sigtimedwait":        true,
		"rt_sigreturn":           true,
		"rt_sigqueueinfo":        true,
		"rt_sigsuspend":          true,
		"tgkill":                 true,
		"sysfs":                  true, // unsupported
		"clone":                  true, // unsupported
		"newfstatat":             true, // unsupported
		"getsid":                 true,
		"getcpu":                 true,
		"mmap":                   true,
		"msync":                  true,
		"mremap":                 true,
		"mprotect":               true,
		"madvise":                true,
		"munmap":                 true,
		"sched_get_priority_min": true,
		"sched_get_priority_max": true,
	}

	specialConsts = map[string]uint64{
		"_LINUX_CAPABILITY_VERSION_1":                         0x19980330,
		"_LINUX_CAPABILITY_VERSION_2":                         0x20071026,
		"_LINUX_CAPABILITY_VERSION_3":                         0x20080522,
		"PROT_NONE":                                           0,
		"O_ASYNC":                                             0x0040,
		"O_TMPFILE":                                           0x022000000,
		"SIGUSR1":                                             30,
		"SIGALRM":                                             14,
		"SIGFPE":                                              8,
		"SIGINT":                                              2,
		"SIG_0":                                               0,
		"SIGBUS":                                              10,
		"SIGIO":                                               23,
		"BUS":                                                 10,
		"USR1":                                                30,
		"ALRM":                                                14,
		"IO":                                                  23,
		"S_ISUID":                                             0x0004000,
		"S_ISGID":                                             0x0002000,
		"RLIM64_INFINITY":                                     ^uint64(0),
		"CLOCK_REALTIME_ALARM":                                8,
		"CLOCK_BOOTTIME_ALARM":                                9,
		"PERF_ATTR_SIZE_VER5":                                 112,
		"PERF_ATTR_SIZE_VER4":                                 104,
		"PERF_ATTR_SIZE_VER3":                                 96,
		"PERF_ATTR_SIZE_VER2":                                 80,
		"PERF_ATTR_SIZE_VER1":                                 72,
		"PERF_ATTR_SIZE_VER0":                                 64,
		"PERF_COUNT_HW_CPU_CYCLES":                            0,
		"PERF_COUNT_HW_INSTRUCTIONS":                          1,
		"PERF_COUNT_HW_CACHE_REFERENCES":                      2,
		"PERF_COUNT_HW_CACHE_MISSES":                          3,
		"PERF_COUNT_HW_BRANCH_INSTRUCTIONS":                   4,
		"PERF_COUNT_HW_BRANCH_MISSES":                         5,
		"PERF_COUNT_HW_BUS_CYCLES":                            6,
		"PERF_COUNT_HW_STALLED_CYCLES_FRONTEND":               7,
		"PERF_COUNT_HW_STALLED_CYCLES_BACKEND":                8,
		"PERF_COUNT_HW_REF_CPU_CYCLES":                        9,
		"PERF_COUNT_SW_CPU_CLOCK":                             0,
		"PERF_COUNT_SW_TASK_CLOCK":                            1,
		"PERF_COUNT_SW_PAGE_FAULTS":                           2,
		"PERF_COUNT_SW_CONTEXT_SWITCHES":                      3,
		"PERF_COUNT_SW_CPU_MIGRATIONS":                        4,
		"PERF_COUNT_SW_PAGE_FAULTS_MIN":                       5,
		"PERF_COUNT_SW_PAGE_FAULTS_MAJ":                       6,
		"PERF_COUNT_SW_ALIGNMENT_FAULTS":                      7,
		"PERF_COUNT_SW_EMULATION_FAULTS":                      8,
		"PERF_COUNT_SW_BPF_OUTPUT":                            10,
		"FUTEX_WAIT_PRIVATE":                                  128,
		"FUTEX_WAKE_PRIVATE":                                  129,
		"FUTEX_WAIT_REQUEUE_PI_PRIVATE":                       139,
		"FUTEX_UNLOCK_PI_PRIVATE":                             135,
		"FUTEX_CMP_REQUEUE_PI_PRIVATE":                        140,
		"MCL_ONFAULT":                                         32768,
		"CAP_CHOWN":                                           0,
		"CAP_DAC_OVERRIDE":                                    1,
		"CAP_DAC_READ_SEARCH":                                 2,
		"CAP_MAC_OVERRIDE":                                    23,
		"CAP_MAC_ADMIN":                                       33,
		"CAP_SYSLOG":                                          34,
		"CAP_BLOCK_SUSPEND":                                   35,
		"CAP_WAKE_ALARM":                                      35,
		"CAP_FOWNER":                                          3,
		"CAP_FSETID":                                          4,
		"CAP_KILL":                                            5,
		"CAP_SETGID":                                          6,
		"CAP_SETUID":                                          7,
		"CAP_SETPCAP":                                         8,
		"CAP_LINUX_IMMUTABLE":                                 9,
		"CAP_NET_BIND_SERVICE":                                10,
		"CAP_NET_BROADCAST":                                   11,
		"CAP_NET_ADMIN":                                       12,
		"CAP_NET_RAW":                                         13,
		"CAP_IPC_LOCK":                                        14,
		"CAP_IPC_OWNER":                                       15,
		"CAP_SYS_MODULE":                                      16,
		"CAP_SYS_RAWIO":                                       17,
		"CAP_SYS_CHROOT":                                      18,
		"CAP_SYS_PTRACE":                                      19,
		"CAP_SYS_PACCT":                                       20,
		"CAP_SYS_ADMIN":                                       21,
		"CAP_SYS_BOOT":                                        22,
		"CAP_SYS_NICE":                                        23,
		"CAP_SYS_RESOURCE":                                    24,
		"CAP_SYS_TIME":                                        25,
		"CAP_SYS_TTY_CONFIG":                                  26,
		"CAP_MKNOD":                                           27,
		"CAP_LEASE":                                           28,
		"CAP_AUDIT_WRITE":                                     29,
		"CAP_AUDIT_CONTROL":                                   30,
		"CAP_SETFCAP":                                         31,
		"CAP_AUDIT_READ":                                      37,
		"FALLOC_FL_COLLAPSE_RANGE":                            0x08,
		"FALLOC_FL_ZERO_RANGE":                                0x10,
		"FALLOC_FL_INSERT_RANGE":                              0x20,
		"FALLOC_FL_UNSHARE_RANGE":                             0x40,
		"KVM_GET_API_VERSION":                                 44544,
		"MEMBARRIER_CMD_QUERY":                                0,
		"MEMBARRIER_CMD_GLOBAL":                               1 << 0,
		"MEMBARRIER_CMD_GLOBAL_EXPEDITED":                     1 << 1,
		"MEMBARRIER_CMD_REGISTER_GLOBAL_EXPEDITED":            1 << 2,
		"MEMBARRIER_CMD_PRIVATE_EXPEDITED":                    1 << 3,
		"MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED":           1 << 4,
		"MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE":          1 << 5,
		"MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_SYNC_CORE": 1 << 6,
		"MEMBARRIER_CMD_SHARED":                               1 << 0,
		"SNDCTL_TMR_START":                                    21506,
		"SIGUSR2":                                             31,
		"SIOCGIWMODE":                                         0x8B07,
		"SIOCGIFCONF":                                         0x8912,
		"PACKET_HOST":                                         0,
		"R_OK":                                                4,
		"W_OK":                                                2,
		"X_OK":                                                1,
		"F_OK":                                                0,
		"O_ACCMODE":                                           3,
		"SIGRTMIN":                                            32,
		"SCHED_OTHER":                                         0,
		"SIGABRT":                                             6,
		"SIGXFSZ":                                             25,
		"SIGCHLD":                                             20,
		"SIGTSTP":                                             18,
		"SIGCONT":                                             19,
		"SHUT_RDWR":                                           2,
		"FS_IOC_GETFLAGS":                                     26113,
		"FS_IOC_SETFLAGS":                                     26112,
		"RTC_UIE_ON":                                          28675,
		"RTC_UIE_OFF":                                         28674,
		"PHN_NOT_OH":                                          28676,
		"RTC_RD_TIME":                                         2149871625,
		"BPF_X":                                               0x8,
		"BPF_K":                                               0,
		"BPF_LD":                                              0x0,
		"BPF_LDX":                                             0x1,
		"BPF_ST":                                              0x2,
		"BPF_STX":                                             0x3,
		"BPF_ALU":                                             0x4,
		"BPF_JMP":                                             0x5,
		"BPF_RET":                                             0x6,
		"BPF_MISC":                                            0x7,
		"BPF_W":                                               0x0,
		"BPF_H":                                               0x8,
		"BPF_B":                                               0x10,
		"BPF_IMM":                                             0,
		"BPF_ABS":                                             0x20,
		"BPF_IND":                                             0x40,
		"BPF_MEM":                                             0x60,
		"BPF_LEN":                                             0x80,
		"BPF_MSH":                                             0xa0,
		"BPF_ADD":                                             0,
		"BPF_SUB":                                             0x10,
		"BPF_MUL":                                             0x20,
		"BPF_DIV":                                             0x30,
		"BPF_OR":                                              0x40,
		"BPF_AND":                                             0x50,
		"BPF_LSH":                                             0x60,
		"BPF_RSH":                                             0x70,
		"BPF_NEG":                                             0x80,
		"BPF_MOD":                                             0x90,
		"BPF_XOR":                                             0xa0,
		"BPF_JA":                                              0x00,
		"BPF_JEQ":                                             0x10,
		"BPF_JGT":                                             0x20,
		"BPF_JGE":                                             0x30,
		"BPF_JSET":                                            0x40,
		"BPF_ALU64":                                           0x07,
		"BPF_DW":                                              0x18,
		"BPF_XADD":                                            0xc0,
		"BPF_MOV":                                             0xb0,
		"BPF_ARSH":                                            0xc0,
		"BPF_END":                                             0xd0,
		"BPF_TO_LE":                                           0x00,
		"BPF_TO_BE":                                           0x08,
		"BPF_FROM_LE":                                         0x00,
		"BPF_FROM_BE":                                         0x08,
		"BPF_JNE":                                             0x50,
		"BPF_JLT":                                             0xa0,
		"BPF_JLE":                                             0xb0,
		"BPF_JSGT":                                            0x60,
		"BPF_JSGE":                                            0x70,
		"BPF_JSLT":                                            0xc0,
		"BPF_JSLE":                                            0xd0,
		"BPF_CALL":                                            0x80,
		"BPF_EXIT":                                            0x90,

		"BPF_REG_0":           0x0,
		"BPF_REG_1":           0x1,
		"BPF_REG_2":           0x2,
		"BPF_REG_3":           0x3,
		"BPF_REG_4":           0x4,
		"BPF_REG_5":           0x5,
		"BPF_REG_6":           0x6,
		"BPF_REG_7":           0x7,
		"BPF_REG_8":           0x8,
		"BPF_REG_9":           0x9,
		"BPF_REG_10":          0x10,
		"MAX_BPF_REG":         0x11,
		"BPF_NOEXIST":         0x1,
		"BPF_EXIST":           0x2,
		"PACKET_MR_MULTICAST": 0,
		"PACKET_MR_PROMISC":   1,
		"PACKET_MR_ALLMULTI":  2,
		"PACKET_MR_UNICAST":   3,
	}
)
